CREATE DATABASE IF NOT EXISTS brujula_db;
USE brujula_db;

CREATE TABLE IF NOT EXISTS objetivos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  direccion VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS puestos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_objetivo INT NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  FOREIGN KEY (id_objetivo) REFERENCES objetivos(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS turnos_config (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_objetivo INT NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fin TIME NOT NULL,
  duracion_horas DECIMAL(5,2) NOT NULL,
  FOREIGN KEY (id_objetivo) REFERENCES objetivos(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vigiladores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  legajo VARCHAR(50) NOT NULL UNIQUE,
  max_horas_mensuales DECIMAL(6,2) NOT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS requerimientos_mensuales (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_puesto INT NOT NULL,
  fecha DATE NOT NULL,
  id_turno_config INT NOT NULL,
  FOREIGN KEY (id_puesto) REFERENCES puestos(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_turno_config) REFERENCES turnos_config(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS asignaciones_cronograma (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_requerimiento INT NOT NULL,
  id_vigilador INT NOT NULL,
  fecha_asignacion DATE NOT NULL,
  estado VARCHAR(50) NOT NULL DEFAULT 'pendiente',
  FOREIGN KEY (id_requerimiento) REFERENCES requerimientos_mensuales(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_vigilador) REFERENCES vigiladores(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
